### ISSUE TITLE
Impossible to export UserGroups

### ISSUE THREAD

**Issue by TG-JC** [PTCInc/thingworx-gitbackup-extension#15]
How to reproduce
- create a new User Group in a project
- open to GitBackup Export dialog box
- select this project
- add the newly created User Group to the selection
- click Export (dialog closes)

What's wrong
- Status dialog box shows nothing: there is no XML pour the User Group we tried to export
- If you push, the commit is empty

Workaround:
- "Export to Source Control" User Groups manualy and download the file on your disk
- git clone the repository locally
- commit on your local repository
- git push to BitBucket
- GitBackup pull to retrieve commited User Group XML

**Comment by cbadici** [comment]
Hi, 
Thanks for pointing out this issue. Indeed I tested with the latest Git extension on ThingWorx 9.1, and the User Groups didn't get exported. This is because the entities are processed by entity type and then moved to the correct folder in the repository. To address this issue quickly, you can go to "Git.Utility.ThingShape" and edit the service: "ExportProjectEntities". 
At line 87, modify _case "UserGroup":_ to _case "Group":_ and then save your the Thing Shape. 
Then, when you try to export user groups, they will appear in your folder. I have attached an image with my result, after this modification. 
![3-18-2021 4-19-36 PM](https://user-images.githubusercontent.com/72975696/111642545-db93a600-8806-11eb-9c0a-e94aad386945.png)

**Comment by TG-JC** [comment]
Hi,
Thank you for the fix. I confirm it works.
I will replicate it on all our environments in the meantime next release is made available.
