### ISSUE TITLE
support token authentication

### ISSUE THREAD

**Issue by TomVergote** [PTCInc/thingworx-gitbackup-extension#18]
According to this post: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ login/password authentication will stop working by August.

This extension probably needs some work to migrate to the new authentication system

**Comment by cbadici** [comment]
Hi @TomVergote , Thanks for your comment and the article. The article you posted might not affect the extension since you have the possibility to generate a personal access token in github and use it instead of the password (https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).  The implementation for the authentication in Java would remain the same. 

However, I have investigated the usage of SSH Keys for authentication and it wouldn't be very large effort to implement this functionality. I will take into account implementing authentication using ssh keys in the next release of the extension.

**Comment by vrosu** [comment]
As of now SSH Keys are not planned to be added as an authentication option because all the Git providers out there support Personal Access Tokens. When that will change, we'll add the SSH keys as well.
