### ISSUE TITLE
importing to 9.0.1 fails

### ISSUE THREAD

**Issue by heteneik** [PTCInc/thingworx-gitbackup-extension#2]
Hi,

Trying to import the extension to 9.0.1 and got the following error:

Extension : infotableselector_ExtensionPackage is already installed. infotableselector_ExtensionPackage:2.2.0 is not compatible, you must remove infotableselector_ExtensionPackage:3.0.1 first.

PS: Sorry I missed there is a new branch for it.

Thanks

**Comment by vrosu** [comment]
I thought this might happen, and apparently now is the time.
I have some questions to ask first:
1. Where did you get the Infotable extension version 3.0? Is it packaged with any of the ThingWorx Apps?
2. Is it possible to delete the version 3.0 of that extension and use my version instead?

I have other questions, but let's take it step by step.

Thanks!

**Comment by heteneik** [comment]
I believe it came packaged with the 9.0.1. I am not sure if I want to delete that as they did so many fixes in 9.0.1 that was broken by 9.0 and I'm not sure if this extension is one of it or not.

**Comment by vrosu** [comment]
It's not part of the base 9.0.1 ThingWorx version, but it is a part of ThingWorx Utilities core - so maybe if you installed that, that's where it's from.
You have two options:
1. remove my infotable extension from the GitBackup package zip file and retry the import process.
2. if you do not use ThingWorx Utilities (dependency for all the other Apps probably), uninstall the 3.0.1 version. It will not have any impact on the base platform.

If you choose option 1, please test the mashup behavior and see if it works fine. The Infotable selector was used to make some buttons disabled or disabled in the Workspace area.

The proper solution would be that I rename the InfotableExtension widget version I'm using to a name that will be unique to my extension - that's what I plan to do this week. I can't use the 3.0.1 version that's embedded there because my version uses additional functionality I developed to make life easier.

**Comment by heteneik** [comment]
Hm, if it didn't come from 9.0.1, it must be Navigate 9.0 than. I'll try the possible options.

Thanks!

**Comment by vrosu** [comment]
Hi @heteneik . I have released version 4.0.1 that contains the renamed infotableselector widget. Can you please test and let me know if it works?
[Release link here](https://github.com/PTCInc/thingworx-gitbackup-extension/releases/tag/V4.0.1 )

**Comment by heteneik** [comment]
Hi @vrosu, it seems it's working fine! Thanks for the quick update.
