### ISSUE TITLE
Removing existing objects

### ISSUE THREAD

**Issue by mpalladi** [PTCInc/thingworx-gitbackup-extension#3]
User guide says - "Version 4.x requires removing any existing 3.x, 2.x or 1.x version (including existing GitBackup Things)"
What is the way to do this ? All my previously imported 3.x objects - "delete option" is greyed out; even as administrator
Is there a service to run , or sequence required.

**Comment by vrosu** [comment]
Removing any existing GitBackup version means removing the extension, the same process done to remove any extension.
But, since that will fail if you have existing GitBackup Things, there is that mention about removing existing GitBackup Things.
Would the following section allow additional context to make the operation clearer?
"-Delete the GitBackup Things that inherit your GitBackup Template. Those are not part of the Extension, so they have the Delete button available.
-Remove the main GitBackup Extension and all it's complementary Extensions from the Manage section."

**Comment by mpalladi** [comment]
That's clearer now, I agree.

**Comment by vrosu** [comment]
Can you please let me know if the process was successful and you were able to import it? That's my trigger to close this issue.

Thanks!

**Comment by mpalladi** [comment]
I wasn't able to import without restarting Thingworx after removing the old extension. These were the fatal errors

- JAR conflict Checking deployed extension JARS [existing: org.eclipse.jgit-5.4.0.201906121030-r.jar, package: org.eclipse.jgit-5.8.1.202007141445-r.jar]
- JAR conflict Checking deployed extension JARS [existing: jsch-0.1.54.jar, package: jsch-0.1.55.jar]
- JAR conflict Checking deployed extension JARS [existing: bcpg-jdk15on-162.jar, package: bcpg-jdk15on-1.66.jar]

After restart import was successful

**Comment by vrosu** [comment]
Ah yes, I have updated the underlying Java libraries and it seems the older java libraries remain there until restart. I will add an intermediary step in those instructions to restart the server. 
Thanks!
