### ISSUE TITLE
Unsure of Commit Status

### ISSUE THREAD

**Issue by mpalladi** [PTCInc/thingworx-gitbackup-extension#4]
I have pushed an initial commit.
After some time, it returns with the following - indicating commit was successful
![image](https://user-images.githubusercontent.com/23260676/92448739-a2d99b00-f1eb-11ea-9f94-dfa950d5b581.png)
But the BitBucket repo is still empty
![image](https://user-images.githubusercontent.com/23260676/92454504-28147e00-f1f3-11ea-81d6-5e4e59b4f151.png)

When I set the repo up, I had to specify it without a user name; my user name has space and I can't change it

**Comment by mpalladi** [comment]
Not I did not do an initial pull, I followed the guide for use case 1 which was just to commit for an initial release.
But I have now tried to Pull, get the following error

- org.eclipse.jgit.api.errors.RefNotAdvertisedException: Remote origin did not advertise Ref for branch master. This Ref may not exist in the remote or may be hidden by permission settings.__ at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:291)

I then Pushed again - but the same result. The push takes a long time, maybe 10 minutes or so
![image](https://user-images.githubusercontent.com/23260676/92469575-9d8a4980-f207-11ea-9ea8-4bb799ed3d89.png)
![image](https://user-images.githubusercontent.com/23260676/92469619-b1ce4680-f207-11ea-8445-0f355ef9ce85.png)

**Comment by vrosu** [comment]
I have just checked with a new bitbucket repo, and the push worked the first time - I mean it created the master branch on the remote.
I did execute Pull before doing Push though (with the same error log as in your case).
Can you check the ApplicationLog and see if there's nothing related to the reason Push fails to work?

**Comment by vrosu** [comment]
I am also not 100% sure what you mean by the phrase "When I set the repo up, I had to specify it without a user name; my user name has space and I can't change it". You wanted to say "when I set the repo up in ThingWorx"? If that's the case, then the GitBackup Thing does not have a correct username setup?

**Comment by mpalladi** [comment]
I have deleted everything, including the local repo and started again. It worked this time when doing a Pull first.

A few other observations and feature improvements

1. A few screenshots in the documentation are out of date  / not in synch with the Mashup.
2. Having 2 buttons for Entity export - is a bit confusing , it would be better when pressing the export button to show all entites, and have the ability of selecting some or all for export
![image](https://user-images.githubusercontent.com/23260676/92547820-5abc8600-f288-11ea-977f-3526455d702d.png)
3. It would be good to be able to sort the exported extensions and multi select extensions not required to be deleted

**Comment by vrosu** [comment]
Thanks @mpalladi & glad you made it work.
Point 1 is known and I'm in process of updating the screens now.
Point 2 you might be right. I specifically put them like this to allow people to export in one click if they would want to export all the entities (the previous behavior). My personal feeling is that specific exports should be the norm - in which case your suggestion should be applied. I'll definitely do it but not now.
Point 3 sorting does work if you click the column names (path, size, etc). Multiselect on the other hand is something I will also keep in mind, as it's definitely useful.
Point 4 From a number of clicks perspective it would be the same as the existing implementation, so the only advantage would be a cognitive easing of the Export Extension process. I would also need to add another mashup to it, so I would say it's a pretty low chance I'll plan for this.

As a quick FYI, I'm working on a log feature right now, because too many things Jgit considers as messages I consider errors, so I'm adding a Log button next to the version that will show the last 500 messages that result from Pull/Push and other methods I'm currently determining.
