### ISSUE TITLE
Git push progress detaills

### ISSUE THREAD

**Issue by jlagares** [PTCInc/thingworx-gitbackup-extension#49]
Is there any way of seeing details of the push  while the "Executing push to git..." message is going on?
in my case it takes almost 20-30 minutes and I'm wondering if I can see any progress in the logs (script or application) 
THank you for your help here!

**Comment by jlagares** [comment]
understood the problem

**Comment by vrosu** [comment]
Out of curiosity, what was the issue?

**Comment by jlagares** [comment]
My project that I work with Ilaria is quite big, the push command takes a
lot of time and it fails some times.
So I’m not able to see if something went wrong in the push until the end.
It would be ideal to see progress of commit
Thanks

**Comment by vrosu** [comment]
In version 5.0.0, the Push service has been modified, so that when it finishes, it adds the timings of its internal operations in the log entry specific to Push in the GitBackup.Log.DataTable. So, based on this work, we at least split in sections the content of this service. I can send these sections to the Script Log if you want, as soon as they are calculated.  This is relatively easy to do. However, displaying in Mashup the progress would require a bit more work to do (and anyway the internal jgit library does not offer progress information, so you'll be able to see only my internal code section progress.)
