### ISSUE TITLE
Unresponsive GitBackup.Main.Mashup

### ISSUE THREAD

**Issue by deepak-chouhan** [PTCInc/thingworx-gitbackup-extension#53]
I have Installed the gitbackup extension in ThingWorx and also setup the credentials. I am having issue while loading the GitBackup.Main.Mashup. The moment when I view the mashup, the page becomes unresponsive.

I am using
- ThingWorx 9.4
- GitBackup Extension version 5.0.0

@pshashipreetham

**Comment by vrosu** [comment]
Hi. Have you checked through another browser? Can you open a private mode and see if this is still repeatable?
Also, did you set the credentials according to the new way of setting credentials in 5.0.0?

**Comment by deepak-chouhan** [comment]
Hi, I tried in private mode, still the same issue, I followed the latest documentation as it is, Is there any additional step required to be done?. Also attaching some logs, not sure if they are gonna help.

<img width="914" alt="Screenshot 2024-01-22 at 10 42 40 AM" src="https://github.com/PTCInc/thingworx-gitbackup-extension/assets/69458937/cb3718bb-60b6-4f50-b0a2-9c9bc5b70e30">

**Comment by pshashipreetham** [comment]
@vrosu, the mashup keeps loading; we have checked all the Logs, and we don't see any issue; when we run the services from Thing, we get the data in a second.

But when we are opening mashup, in the Runtime, Services like:
1. GetConfiguration won't end its execution
2. GetBranchList

Has anyone else had this issue before? Because we could run properly with an older version of the GitHub extension, we are facing the issue with the latest one.

We are on Thingworx 9.4.3

**Comment by vrosu** [comment]
@pshashipreetham sorry for the delay. I'm not sure what the issue might be. It works fine in 9.4. Looking at the first error log, I see there's an error about the "cannot lock" a file. Have you set proper permissions for the FileRepository folder on disk to Tomcat's user? A quick way to check this is if you can upload a file in a ThingWorx file repository.
