### ISSUE TITLE
Import of User Entities Error after configuring the GitBackup Extension

### ISSUE THREAD

**Issue by Sh1rkh4n** [PTCInc/thingworx-gitbackup-extension#59]
The following Application error occurs when importing User Entity either using the Composer Import functionality, or using the GitBackup Import button:
**"Unable to process import org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]"**

Checked: if extension is removed, or not yet configured, the Import works as expected.

Steps to reproduce the error:

1. Install extension accordingto the user guide
2. Create a new GitThing through the GitBackup mashup.
3. Configure the GitThing, with data, and User Credentials
4. Check if data from remote repo can be pulled
5. Try to export any User Entity using the Composer , or the GitBackup Export functions.
6. Import back the same User Entity using and of the imports mentioned previously.

I'm not sure, but error perhaps related to UserExtension, GitCredentials infotable, which was introduced in v5.0
Other entity imports (mashups,things) seem to be working as normal so far!

------------------------
App version. ThingWorx 9.3.2-b411 
Extension version: 5.0.0 & 5.0.1

**Comment by vrosu** [comment]
Hi @Sh1rkh4n,
At its core this was a platform bug, which was fixed in ThingWorx 9.6.0 (see what's fixed section [here](https://support.ptc.com/help/thingworx/platform/r9.6/en/?_gl=1*dvmeli*_ga*MTc1NDI1NTYwMy4xNzE5NTY2MTM0*_ga_CBN5QVB9VJ*MTcxOTU3MzAyMy4yLjEuMTcxOTU3MzAyMy4wLjAuMA..*_gcl_au*MzAyNDkwMDk2LjE3MTk1NjYxMzQ.*_ga_7NMP2MSYPM*MTcxOTU3MTE4MS4yLjEuMTcxOTU3MzAyNS41OC4wLjA.#page/ThingWorx/Help/Release_Notes/FixedIssues/Fixed_Issues_in_ThingWorx_Platform_9_6_0_0.html#)). Search this Jira ID: TW-110554. 
This bug was indeed triggered by the fact the credentials are stored now in the Infotable in the UserExtensions ThingShape.
Regarding the fix version: please see if the same bug was fixed in either 9.4 or 9.5 - it will probably be fixed there in the latest releases, but I did not check their release notes.

**Comment by vrosu** [comment]
I set the label as won't fix, because it's a platform bug, hence I won't fix it from my end.

**Comment by Sh1rkh4n** [comment]
Hi, thanks for the explanation. Twx update will fix this. 
I'll close the case.
